[package]
name = "just-func"
description = "just-func in Rust"
readme = "README.md"
keywords = ["just-func", "functional"]
categories = ["no-std"]
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
documentation.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
