[package]
name = "just-func"
version = "0.0.0-alpha"
authors = ["Homa Wong <homawong@gmail.com>"]
license = "MIT"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
